secrets: /config/secrets.yaml
logs:
  main_log:
    filename: /config/appdaemon/info.log
  error_log:
    filename: /config/appdaemon/info.log
appdaemon:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
http:
  # Required for now: https://community.home-assistant.io/t/announcement-appdaemon-4-0-0-beta-2/143304/3
  url: http://0.0.0.0:5050
