secrets: /config/secrets.yaml
log:
  logfile: /config/appdaemon/info.log
  errorfile: /config/appdaemon/info.log
  accessfile: /config/appdaemon/info.log
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: fdc301c05b0a40f48c78ebf5aec5bc83
hadashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards
