secrets: /config/secrets.yaml
log:
  logfile: /config/appdaemon/info.log
  errorfile: /config/appdaemon/info.log
  accessfile: /config/appdaemon/info.log
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
