util:
  module: util
  class: Util

lights_schedule:
  module: lights_schedule
  class: LightsSchedule

temp_control:
  module: temp_control
  class: TempControl
  constrain_start_time: "23:00:00"
  constrain_end_time: "07:00:00"
  min_temp: 65
  max_temp: 70
  climate_entity: climate.dining_room_nest
  # The temperature sensor to use to control temperature.
  sensor_temp: sensor.sn1_temperature

laundry_room_light:
  module: door_activated_light
  class: DoorActivatedLight
  light: light.laundry_room
  door_sensor: binary_sensor.laundry_room_door_sensor_contact
  # How long to leave the light on before turning it off automatically, in seconds.
  delay: 5400

uility_room_light:
  module: door_activated_light
  class: DoorActivatedLight
  light: light.utility_room
  door_sensor: binary_sensor.utility_room_door_sensor_contact
  # How long to leave the light on before turning it off automatically, in seconds.
  delay: 1800
