# Arriving at home (Away -> Home/Asleep). Turn off "eco" mode on thermostat.
- alias: 'Away Mode Deacitvated'
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      from: 'Away'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.dining_room_nest
        preset_mode: 'none'

# Going to sleep. Turn off all lights.
- alias: 'Asleep Mode Activated'
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Asleep'
  action:
    - service: light.turn_off
      entity_id: all

# Leaving the house. Set thermostat to "eco" mode.
- alias: 'Away Mode Activated'
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Away'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.dining_room_nest
        preset_mode: 'eco'

- alias: 'Wake Up'
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: 'input_select.house_mode'
      state: 'Asleep'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: 'Home'
