###############################
#
#  Basic Info and Configuration
#
###############################

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_timezone
  # Customization file
  # customize: !include customize.yaml
  customize: !include customize.yaml

# Database options
recorder:
  db_url: !secret mariadb_url

# HTTP options
http:
  base_url: !secret http_base_url

# Enable logging
logger:

# System health component
system_health:

# Enables Home Assistant configuration GUI (integrations, users, server, etc.)
config:

# Enables the frontend
frontend:

# Enable Lovelace YAML configuration
lovelace:
  mode: yaml

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#########################
#
#  Components and Sensors
#
#########################

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

binary_sensor:
  - platform: huesensor

sensor:
  - platform: huesensor

  #### DARKSKY #################################################################
  - platform: darksky
    api_key: !secret dark_sky_api_key
    monitored_conditions:
     - summary
     - icon
     - nearest_storm_distance
     - precip_type
     - precip_intensity
     - precip_probability
     - temperature
     - apparent_temperature
     - dew_point
     - wind_speed
     - wind_bearing
     - cloud_cover
     - humidity
     - pressure
     - visibility
     - ozone
     - minutely_summary
     - hourly_summary
     - daily_summary

  #### SENSORNODE 1 ############################################################
  - platform: mqtt
    state_topic: !secret sensornode1_name
    name: "SN1 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode1_name
    name: "SN1 LDR"
    # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'
  - platform: mqtt
    state_topic: !secret sensornode1_name
    name: "SN1 Motion"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: !secret sensornode1_name
    name: "SN1 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode1_name
    name: "SN1 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  #### SENSORNODE 2 ############################################################
  - platform: mqtt
    state_topic: !secret sensornode2_name
    name: "SN2 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode2_name
    name: "SN2 LDR"
    # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'
  - platform: mqtt
    state_topic: !secret sensornode2_name
    name: "SN2 Motion"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: !secret sensornode2_name
    name: "SN2 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode2_name
    name: "SN2 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  #### SENSORNODE 3 ############################################################
  - platform: mqtt
    state_topic: !secret sensornode3_name
    name: "SN3 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode3_name
    name: "SN3 LDR"
    # This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'
  - platform: mqtt
    state_topic: !secret sensornode3_name
    name: "SN3 Motion"
    value_template: '{{ value_json.motion }}'
  - platform: mqtt
    state_topic: !secret sensornode3_name
    name: "SN3 Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: !secret sensornode3_name
    name: "SN3 Real Feel"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'

#### FITBIT ##################################################################
  - platform: fitbit
    clock_format: 12H
    monitored_resources:
      - "body/weight"
      - "activities/steps"
      - "activities/floors"
      - "activities/distance"
      - "activities/calories"
      - "activities/minutesLightlyActive"
      - "body/bmi"
      - "body/fat"
      - "devices/battery"
      - "activities/heart"

# Text to speech
tts:
  - platform: google_translate

# Cloud
cloud:

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Chamberlain MyQ
cover:
  - platform: myq
    username: !secret myq_cover_username
    password: !secret myq_cover_password
    type: chamberlain

person:
  - name: mm
    id: mm
    device_trackers:
      - device_tracker.mmphone
      - device_tracker.google_maps_102300921053278247904
  - name: nl
    id: nl
    device_trackers:
      - device_tracker.nlphone
      - device_tracker.google_maps_105598837437051787295

device_tracker:
  - platform: ddwrt
    host: !secret router_ip
    port: 8080
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
  - platform: google_maps
    username: !secret google_maps_username
    max_gps_accuracy: 200

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 40
    icon: mdi:home
  - name: !secret mmwork_name
    latitude: !secret mmwork_latitude
    longitude: !secret mmwork_longitude
    radius: 80
    icon: mdi:briefcase
  - name: !secret nlwork_name
    latitude: !secret nlwork_latitude
    longitude: !secret nlwork_longitide
    radius: 250
    icon: mdi:briefcase
  - name: !secret amhome_name
    latitude: !secret amhome_latitude
    longitude: !secret amhome_longitide
    radius: 250
    icon: mdi:home

ffmpeg:
camera:
  - platform: ffmpeg
    name: Front Window Camera
    input: !secret cam1_input
    extra_arguments: '-r 4 -vf "scale=640:360"'
  - platform: ffmpeg
    name: Kitchen Camera
    input: !secret cam2_input
    extra_arguments: '-r 4 -vf "scale=640:360"'
  - platform: ffmpeg
    name: ddot_toll_plaza_entrance
    input: !secret ddot_toll_plaza_entrance_input
    extra_arguments: '-r 4 -vf "scale=640:360"'
  - platform: ffmpeg
    name: ddot_toll_plaza_exit
    input: !secret ddot_toll_plaza_exit_input
    extra_arguments: '-r 4 -vf "scale=640:360"'

mqtt:
  broker: localhost
  port: 1883
  client_id: hassio-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

input_select:
  house_mode:
    name: House Mode
    options:
      - Home
      - Asleep
      - Away
  temp_reg:
    name: Temperatute Regulation
    options:
      - Normal
      - Nighttime

input_boolean:
  light_cycle:
    name: Rainbow Lights

group: !include groups.yaml
automation: !include automation.yaml
