title: !secret home_name
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router

resources:
  - url: /local/circle-sensor-card.js?v=1
    type: module
  - url: /local/thermostat-element.js?v=QQQ000000QQQ
    type: module

views:
    # View tab title.
  - icon: mdi:home-assistant
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.mmphone
          - device_tracker.nlphone
        state_filter:
          - 'home'
        card_config:
          type: glance
          title: Whereabouts
      - type: history-graph
        title: 'Presence'
        entities:
          - device_tracker.mmphone
          - device_tracker.nlphone
        hours_to_show: 24
        refresh_interval: 60
      - type: entities
        entities:
          - light.living_room
          - light.back_hall
          - light.hue_master_bedroom
          - light.master_bedroom_ceiling
          - light.laundry_room
          - binary_sensor.laundry_room_door_sensor_contact
          - binary_sensor.utility_room_door_sensor_contact

  - icon: mdi:thermometer
    title: Climate
    cards:
      - type: entities
        entities:
          - entity: climate.dining_room_nest
            name: Thermostat
          - entity: sensor.sn1_temperature
            name: Bedroom
      - type: history-graph
        title: 'Temperature'
        entities:
          - sensor.sn1_temperature
          - sensor.dining_room_thermostat_nest_temperature
          - sensor.dining_room_thermostat_nest_hvac_state
        hours_to_show: 24
        refresh_interval: 60
      - type: history-graph
        title: 'Humidity'
        entities:
          - sensor.sn1_humidity
          - sensor.dining_room_thermostat_nest_humidity
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:floor-plan
    title: Floor Plan
    cards:
      - type: picture-elements
        # title: '1st Floor'
        image: /local/floorplan-main.svg?v=QQQ000000QQQ
        elements:
          - type: custom:thermostat-element
            entity: climate.dining_room_nest
            hvac_state: sensor.dining_room_thermostat_nest_hvac_state
            style:
              top: 60.68%
              left: 55.19%
          # Device Trackers
          - type: state-icon
            entity: device_tracker.mmphone
            style:
              top: 20.26%
              left: 31.73%
          - type: state-icon
            entity: device_tracker.nlphone
            style:
              top: 28.26%
              left: 31.73%
          # Cameras
          - type: state-icon
            entity: camera.front_window_camera
            style:
              top: 95.32%
              left: 72.47%
          - type: state-icon
            entity: camera.kitchen_camera
            style:
              top: 80%
              left: 80%
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 30.04%
              left: 18.40%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 42.05%
              left: 20.49%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.living_room
            style:
              top: 12.40%
              left: 28.15%
          # Doors
          - type: image
            image: /local/red.png
            entity: cover.garage_door_opener
            style:
              top: 98.63%
              left: 21%
              width: 25%
              height: 1.22%
            state_filter:
              "open": opacity(100%)
              "closed": opacity(0%)
          - type: image
            image: /local/green.png
            entity: cover.garage_door_opener
            style:
              top: 98.63%
              left: 21%
              width: 25%
              height: 1.22%
            state_filter:
              "open": opacity(0%)
              "closed": opacity(100%)
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity: media_player.apple_tv
            style:
              top: 13.31%
              left: 85.19%
          # Inactive
          - type: icon # Dining Room
            icon: mdi:lightbulb
            style:
              top: 49.43%
              left: 72.84%
              color: gray
              opacity: 0.5
          - type: icon # Living Room North
            icon: mdi:lightbulb
            style:
              top: 23.95%
              left: 82.22%
              color: gray
              opacity: 0.5
          - type: icon # Living Room Southeast
            icon: mdi:lightbulb
            style:
              top: 36.09%
              left: 28.15%
              color: gray
              opacity: 0.5
          - type: icon # Kitchen
            icon: mdi:lightbulb
            style:
              top: 73.62%
              left: 72.84%
              color: gray
              opacity: 0.5
      - type: picture-elements
        # title: 'Basement'
        image: /local/floorplan-basement.svg?v=QQQ000000QQQ
        elements:
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.laundry_room
            style:
              top: 20.59%
              left: 14.44%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.laundry_room
            style:
              top: 29.10%
              left: 14.44%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.utility_room
            style:
              top: 81.25%
              left: 71.52%
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity:  media_player.roku_streaming_stick
            style:
              top: 78.48%
              left: 51.20%
          - type: state-icon
            tap_action:
              action: more-info
            entity:  media_player.xbr75x900e
            style:
              top: 14.37%
              left: 69.51%
      - type: picture-elements
        # title: 'Upstairs'
        image: /local/floorplan-upstairs.svg?v=QQQ000000QQQ
        elements:
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.hue_master_bedroom
            style:
              top: 35.59%
              left: 43.09%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.master_bedroom_ceiling
            style:
              top: 24.16%
              left: 58.02%
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity: media_player.chromecast
            style:
              top: 13.31%
              left: 85.19%

  - icon: mdi:lock-open
    title: Security
    cards:
      - type: picture-entity
        entity: camera.front_window_camera
      - type: picture-entity
        entity: camera.kitchen_camera
      - type: entities
        entities:
          - entity: cover.garage_door_opener
            secondary_info: last-changed
      - type: history-graph
        title: 'Motion'
        entities:
          - sensor.sn1_motion
          - cover.garage_door_opener
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:television-classic
    title: Media
    cards:
      - type: entities
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
      - type: history-graph
        title: 'Media History'
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:car-side
    title: Travel
    cards:
      - type: picture-entity
        name: 'Delaware Toll Plaza Entrance'
        entity: camera.ddot_toll_plaza_entrance
      - type: picture-entity
        name: 'Delaware Toll Plaza Exit'
        entity: camera.ddot_toll_plaza_exit

  - icon: mdi:run
    title: Fitness
    cards:
    - !include lovelace/fitbit.yaml
