title: !secret home_name
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
  
resources:
  - url: /local/circle-sensor-card.js?v=1
    type: module

views:
    # View tab title.
  - icon: mdi:home-assistant
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.mmphone
          - device_tracker.nlphone
        state_filter:
          - 'home'
        card_config:
          type: glance
          title: Whereabouts
      - type: history-graph
        title: 'Presence'
        entities:
          - device_tracker.mmphone
          - device_tracker.nlphone
        hours_to_show: 24
        refresh: 60
      - type: entities
        entities:
          - light.living_room
          - light.back_hall
          - light.hue_master_bedroom
          - light.master_bedroom_ceiling
          - binary_sensor.laundry_room_door

  - icon: mdi:thermometer
    title: Climate
    cards:
      - type: entities
        entities:
          - entity: climate.dining_room_nest
            name: Thermostat
          - entity: sensor.sn1_temperature
            name: Bedroom
      - type: history-graph
        title: 'Temperature'
        entities:
          - sensor.sn1_temperature
          - sensor.dining_room_thermostat_nest_temperature
          - sensor.dining_room_thermostat_nest_hvac_state
        hours_to_show: 24
        refresh: 60
      - type: history-graph
        title: 'Humidity'
        entities:
          - sensor.sn1_humidity
          - sensor.dining_room_thermostat_nest_humidity
        hours_to_show: 24
        refresh: 60

  - icon: mdi:floor-plan
    title: Floor Plan
    cards:
      - type: picture-elements
        title: '1st Floor'
        image: /local/floorplan-main.svg
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 28.4%
              left: 18.5%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 40.7%
              left: 20.6%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.living_room
            style:
              top: 10.4%
              left: 28.3%
          - type: state-label
            entity: sensor.dining_room_thermostat_nest_temperature
            style:
              top: 56%
              left: 61%
              color: blue
              font-size: 14pt
              font-weight: bold
          - type: image
            image: /local/red.png
            entity: cover.garage_door_opener
            style:
              top: 50%
              left: 50%
              width: 10%
              height: 1%
            state_filter:
              "open": opacity(100%)
              "closed": opacity(0%)
          - type: image
            image: /local/green.png
            entity: cover.garage_door_opener
            style:
              top: 50%
              left: 50%
              width: 10%
              height: 1%
            state_filter:
              "open": opacity(0%)
              "closed": opacity(100%)

  - icon: mdi:lock-open
    title: Security
    cards:
      - type: picture-entity
        entity: camera.indoorcam1
      - type: picture-entity
        entity: camera.indoorcam2
      - type: entities
        entities:
          - entity: cover.garage_door_opener
            secondary_info: last-changed
      - type: history-graph
        title: 'Motion'
        entities:
          - sensor.sn1_motion
          - cover.garage_door_opener
        hours_to_show: 24
        refresh: 60

  - icon: mdi:television-classic
    title: Media
    cards:
      - type: entities
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
      - type: history-graph
        title: 'Media History'
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
        hours_to_show: 24
        refresh: 60
  
  - icon: mdi:run
    title: Fitness
    cards: 
    - !include lovelace/fitbit.yaml