title: !secret home_name
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router

resources:
  - url: /local/circle-sensor-card.js?v=1
    type: module
  - url: /local/thermostat-element.js?v=QQQ507183QQQ
    type: module

views:
  - icon: mdi:floor-plan
    title: Floor Plan
    cards:
      - type: picture-elements
        # title: '1st Floor'
        image: /local/floorplan-main.svg?v=QQQ507183QQQ
        elements:
          # Weather
          - type: state-label
            entity: sensor.dark_sky_temperature
            style:
              top: 5.00%
              left: 7.00%
          - type: state-label
            entity: sensor.dark_sky_summary
            style:
              top: 5.00%
              left: 25.00%
          # Thermostat
          - type: custom:thermostat-element
            entity: climate.dining_room_nest
            style:
              top: 60.68%
              left: 55.19%
          # Device Trackers
          - type: state-icon
            entity: person.mm
            style:
              top: 20.26%
              left: 31.73%
          - type: state-icon
            entity: person.nl
            style:
              top: 28.26%
              left: 31.73%
          # Cameras
          - type: state-icon
            entity: camera.front_window_camera
            style:
              top: 95.32%
              left: 72.47%
          - type: state-icon
            entity: camera.kitchen_camera
            style:
              top: 80%
              left: 80%
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 30.04%
              left: 18.40%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.back_hall
            style:
              top: 42.05%
              left: 20.49%
          - type: state-icon # Living Room 1
            tap_action:
              action: toggle
            entity: light.living_room
            style:
              top: 13.48%
              left: 28.15%
          - type: state-icon # Living Room 2
            tap_action:
              action: toggle
            entity: light.living_room
            style:
              top: 35.04%
              left: 28.15%
          - type: state-icon # Living Room 3
            tap_action:
              action: toggle
            entity: light.living_room
            style:
              top: 23.95%
              left: 82.22%
          - type: state-icon # Kitchen
            tap_action:
              action: toggle
            entity: switch.kitchen_switch
            icon: mdi:lightbulb
            style:
              top: 73.62%
              left: 72.84%
          - type: state-icon # Dining Room
            tap_action:
              action: toggle
            entity: light.dining_room_dimmer
            style:
              top: 49.43%
              left: 72.84%
          # Doors
          - type: image
            image: /local/red.png
            entity: cover.garage_door_opener
            style:
              top: 98.63%
              left: 21%
              width: 25%
              height: 1.22%
            state_filter:
              "open": opacity(100%)
              "closed": opacity(0%)
          - type: image
            image: /local/green.png
            entity: cover.garage_door_opener
            style:
              top: 98.63%
              left: 21%
              width: 25%
              height: 1.22%
            state_filter:
              "open": opacity(0%)
              "closed": opacity(100%)
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity: media_player.apple_tv
            style:
              top: 13.31%
              left: 85.19%
          # Inactive
          # None
      - type: picture-elements
        # title: 'Basement'
        image: /local/floorplan-basement.svg?v=QQQ507183QQQ
        elements:
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.laundry_room
            style:
              top: 20.59%
              left: 14.44%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.laundry_room
            style:
              top: 29.10%
              left: 14.44%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.utility_room
            style:
              top: 81.25%
              left: 71.52%
          - type: state-icon # Basement West 1
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 18.94%
              left: 44.42%
          - type: state-icon # Basement West 2
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 18.94%
              left: 59.42%
          - type: state-icon # Basement West 3
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 18.94%
              left: 74.42%
          - type: state-icon # Basement West 4
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 30.09%
              left: 44.42%
          - type: state-icon # Basement West 5
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 30.09%
              left: 59.42%
          - type: state-icon # Basement West 6
            tap_action:
              action: toggle
            entity: light.basement_dimmer
            style:
              top: 30.09%
              left: 74.42%
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity:  media_player.roku_streaming_stick
            style:
              top: 78.48%
              left: 51.20%
          - type: state-icon
            tap_action:
              action: more-info
            entity:  media_player.xbr75x900e
            style:
              top: 14.37%
              left: 69.20%
          # Temperature
          - type: state-label
            entity: sensor.sn2_temperature
            style:
              top: 49.60%
              left: 64.35%
          # Inactive
          ###
      - type: picture-elements
        # title: 'Upstairs'
        image: /local/floorplan-upstairs.svg?v=QQQ507183QQQ
        elements:
          # Service Buttons
          # USe this for more advanced Input Select business.
          # https://community.home-assistant.io/t/input-select-select-option-template/110228
          - type: service-button
            title: Sleep
            service: input_select.select_option
            service_data:
              entity_id: input_select.house_mode
              option: Asleep
            style:
              top: 34.10%
              left: 58.02%
          # Lights
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.hue_master_bedroom
            style:
              top: 35.59%
              left: 43.09%
          # Media Players
          - type: state-icon
            tap_action:
              action: more-info
            entity: media_player.chromecast
            style:
              top: 14.52%
              left: 83.17%
          # Inactive
          - type: icon # Master Bedroom Ceiling
            icon: mdi:lightbulb
            style:
              top: 24.16%
              left: 58.02%
              color: gray
              opacity: 0.5
          # Temperature
          - type: state-label
            entity: sensor.sn1_temperature
            style:
              top: 15.00%
              left: 58.02%

  - icon: mdi:home-assistant
    title: Overview
    # theme: dark-mode
    cards:
      - type: entities
        title: Select Mode
        entities:
          - input_select.temp_reg
          - input_select.house_mode
      - type: entities
        title: Automation
        entities:
          - input_boolean.light_cycle
      - type: history-graph
        title: 'Presence'
        entities:
          - entity: person.mm
            name: !secret mm_name
          - entity: person.nl
            name: !secret nl_name
        hours_to_show: 24
        refresh_interval: 60
      - type: entities
        entities:
          - light.living_room
          - light.back_hall
          - light.master_bedroom
          - light.laundry_room
          - binary_sensor.laundry_room_door_sensor_contact
          - binary_sensor.utility_room_door_sensor_contact

  - icon: mdi:thermometer
    title: Climate
    cards:
      - type: entities
        entities:
          - entity: climate.dining_room_nest
            name: Thermostat
          - entity: sensor.sn1_temperature
            name: Bedroom
          - entity: sensor.sn2_temperature
            name: Basement
          - entity: sensor.sn3_temperature
            name: Living Room
      - type: history-graph
        title: 'Temperature'
        entities:
          - entity: sensor.sn1_temperature
            name: Bedroom
          - entity: sensor.sn2_temperature
            name: Basement
          - entity: sensor.sn3_temperature
            name: Living Room
          - entity: sensor.dining_room_thermostat_nest_temperature
            name: Nest
          - entity: sensor.dining_room_thermostat_nest_hvac_state
            name: HVAC State
        hours_to_show: 24
        refresh_interval: 60
      - type: history-graph
        title: 'Humidity'
        entities:
          - entity: sensor.sn1_humidity
            name: Bedroom
          - entity: sensor.sn2_humidity
            name: Basement
          - entity: sensor.sn3_humidity
            name: Living Room
          - entity: sensor.dining_room_thermostat_nest_humidity
            name: Nest
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:lock-open
    title: Security
    cards:
      - type: picture-entity
        entity: camera.front_window_camera
      - type: picture-entity
        entity: camera.kitchen_camera
      - type: entities
        entities:
          - entity: cover.garage_door_opener
            secondary_info: last-changed
      - type: history-graph
        title: 'Motion'
        entities:
          - entity: person.mm
            name: !secret mm_name
          - entity: person.nl
            name: !secret nl_name
          - entity: sensor.sn1_motion
            name: Bedroom
          - entity: sensor.sn2_motion
            name: Basement
          - entity: sensor.sn3_motion
            name: Living Room
          - cover.garage_door_opener
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:television-classic
    title: Media
    cards:
      - type: entities
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
      - type: history-graph
        title: 'Media History'
        entities:
          - media_player.apple_tv
          - media_player.chromecast
          - media_player.roku_player
          - media_player.roku_streaming_stick
          - media_player.ubpx800
          - media_player.xbr75x900e
        hours_to_show: 24
        refresh_interval: 60

  - icon: mdi:car-side
    title: Travel
    cards:
      - type: map
        aspect_ratio: 16:9
        default_zoom: 8
        entities:
          - person.mm
          - person.nl
          - zone.home
      - type: picture-entity
        name: 'Delaware Toll Plaza Entrance'
        entity: camera.ddot_toll_plaza_entrance
      - type: picture-entity
        name: 'Delaware Toll Plaza Exit'
        entity: camera.ddot_toll_plaza_exit

  - icon: mdi:run
    title: Fitness
    cards:
    - !include lovelace/fitbit.yaml
